# Etapa 1: construir la app
FROM node:20 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build:local

# Etapa 2: NGINX
FROM nginx:alpine

# Borra configuración por defecto
RUN rm /etc/nginx/conf.d/default.conf

# Copia tu config personalizada
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia el build de React
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
